var str1 = 'hello';
var str2 = 'world';
console.log(str1 == str2);
console.log(str1 != str2);
var upperCaseStr = 'HELLO';
var lowerCaseStr = 'hello';
console.log(upperCaseStr.toLowerCase() == lowerCaseStr);
var num1 = 5;
var num2 = 10;
console.log(num1 == num2);
console.log(num1 != num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
var condition1 = true;
var condition2 = false;
console.log(condition1 && condition2);
console.log(condition1 || condition2);
var fruits = ['apple', 'orange', 'banana'];
console.log(fruits.indexOf('banana') !== -1);
console.log(fruits.indexOf('grape') === -1);
